### ISSUE TITLE
"issue template" link broken

### ISSUE THREAD

**Issue by cypayne** [DSI-CORES/OpenByDesign#40]
Link to "issue template" in "CONTRIBUTING.md" under "Making a change with a pull request" Section 1 routes to 404.

**Comment by franklin-feingold** [comment]
thank you for surfacing this! the contributing guide was adapted from another group's contributing guide (https://the-turing-way.netlify.app/welcome) - i'll open an issue to redirect to our pages/make a todo for resources we do not have yet (e.g. the issue templates you were looking for)

**Comment by cypayne** [comment]
sounds great!
